import { BASE_URL } from "./route";

export const CLIENT_ROUTES = {
  REFRESH_TOKEN: `${BASE_URL.CLIENT}/refresh-token`,
  REFRESH_SESSION: `${BASE_URL.CLIENT}/refresh-session`,
  SAVE_FCM_TOKEN: `${BASE_URL.CLIENT}/save-fcm-token`,
  NOTIFICATIONS: `${BASE_URL.CLIENT}/notifications`,
  MARK_NOTIFICATION_READ: `${BASE_URL.CLIENT}/notifications/read`,
  SEND_OTP: `${BASE_URL.CLIENT}/send-otp`,
  SIGNUP: `${BASE_URL.CLIENT}/signup`,
  LOGIN: `${BASE_URL.CLIENT}/login`,
  GOOGLE_AUTH: `${BASE_URL.CLIENT}/google-auth`,
  FORGOT_PASSWORD: `${BASE_URL.CLIENT}/forgot-password`,
  RESET_PASSWORD: `${BASE_URL.CLIENT}/reset-password`,
  CATEGORIES: `${BASE_URL.CLIENT}/categories`,
  DETAILS: `${BASE_URL.CLIENT}/details`,
  CHANGE_PASSWORD: `${BASE_URL.CLIENT}/change-password`,
  SERVICES: `${BASE_URL.CLIENT}/services`,
  SERVICE_BY_ID: (id: string) => `${BASE_URL.CLIENT}/services/${id}`,
  BOOK_SERVICE: (id: string) => `${BASE_URL.CLIENT}/services/${id}/book`,
  RESCHEDULE_BOOKING: (bookingId: string) => `${BASE_URL.CLIENT}/bookings/${bookingId}/reschedule`,
  BOOKINGS: `${BASE_URL.CLIENT}/bookings`,
  CREATE_BOOKING_PAYMENT: `${BASE_URL.CLIENT}/create-booking-payment`,
  CONFIRM_PAYMENT: `${BASE_URL.CLIENT}/confirm-payment`,
  CANCEL_BOOKING: (bookingId: string) => `${BASE_URL.CLIENT}/cancel-booking/${bookingId}`,
  WALLET: `${BASE_URL.CLIENT}/wallet`,
  WALLET_AMOUNT: `${BASE_URL.CLIENT}/wallet/amount`,
  REVIEW: `${BASE_URL.CLIENT}/review`,
  REVIEWS: `${BASE_URL.CLIENT}/reviews`,
  WORK_SAMPLES_BY_VENDOR: (vendorId: string) => `${BASE_URL.CLIENT}/work-sample/${vendorId}`,
  LOGOUT: `${BASE_URL.CLIENT}/logout`,
};